#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Nov 29, 2018 01:28:02 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import about_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    about_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    about_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font12 = "-family Meiryo -size 14 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font13 = "-family {Meiryo UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font16 = "-family Fixedsys -size 14 -weight bold -slant roman "  \
            "-underline 1 -overstrike 0"
        font17 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family Fixedsys -size 22 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("795x606+538+251")
        top.title("New Toplevel")
        top.configure(background="#3f7cd8")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.013, rely=0.033, height=56, width=172)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#3f7cd8")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#e6c9ff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''About :''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.088, rely=0.132, height=40, width=624)
        self.Label2.configure(background="#3f7cd8")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''This project was made as a part of open ended activity''')
        self.Label2.configure(width=624)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.013, rely=0.792, height=26, width=225)
        self.Label3.configure(background="#3f7cd8")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font16)
        self.Label3.configure(foreground="#e6c9ff")
        self.Label3.configure(highlightbackground="#f0f0f0")
        self.Label3.configure(text='''Course Instructor :''')
        self.Label3.configure(width=225)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.654, rely=0.792, height=26, width=103)
        self.Label4.configure(background="#3f7cd8")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font16)
        self.Label4.configure(foreground="#e6c9ff")
        self.Label4.configure(text='''Guide :''')
        self.Label4.configure(width=103)

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.075, rely=0.842, height=37, width=122)
        self.Label5.configure(background="#3f7cd8")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font17)
        self.Label5.configure(foreground="#ffffff")
        self.Label5.configure(text='''Madhura S''')

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.566, rely=0.842, height=66, width=242)
        self.Label6.configure(background="#3f7cd8")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font17)
        self.Label6.configure(foreground="#ffffff")
        self.Label6.configure(text='''K.M.M Rajashekariah''')
        self.Label6.configure(width=242)

        self.Label7 = tk.Label(top)
        self.Label7.place(relx=0.189, rely=0.198, height=35, width=464)
        self.Label7.configure(background="#3f7cd8")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font=font13)
        self.Label7.configure(foreground="#ffffff")
        self.Label7.configure(text='''at SoCSE, KLE Technological University.''')

        self.Label8 = tk.Label(top)
        self.Label8.place(relx=0.553, rely=0.297, height=265, width=277)
        self.Label8.configure(background="#3f7cd8")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self._img1 = tk.PhotoImage(file="./kletech_logo.png")
        self.Label8.configure(image=self._img1)
        self.Label8.configure(text='''Label''')
        self.Label8.configure(width=277)

        self.Label9 = tk.Label(top)
        self.Label9.place(relx=0.075, rely=0.297, height=267, width=284)
        self.Label9.configure(background="#ffffff")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self._img2 = tk.PhotoImage(file="./logo[0].png")
        self.Label9.configure(image=self._img2)
        self.Label9.configure(text='''Label''')
        self.Label9.configure(width=284)

if __name__ == '__main__':
    vp_start_gui()





