#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Nov 28, 2018 05:53:37 PM IST  platform: Windows NT

import sys
import numpy as np
import tkinter.messagebox as fmsgbox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import SLP_Main_Page_support
import SLP_support
import about_support


def start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    SLP_Main_Page_support.init(root, top)
    root.mainloop()


def about():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root.destroy()
    root = tk.Tk()
    top = Toplevel3(root)
    about_support.init(root, top)
    root.mainloop()


def start_eqn():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root.destroy()
    root = tk.Tk()
    top = Toplevel2(root)
    SLP_support.init(root, top)
    root.mainloop()


def go_back():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root.destroy()
    root = tk.Tk()
    top = Toplevel1(root)
    about_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    SLP_Main_Page_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        font12 = "-family {Lucida Calligraphy} -size 30 -weight bold "  \
            "-slant roman -underline 1 -overstrike 0"
        font15 = "-family {Segoe UI Symbol} -size 16 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font20 = "-family {Lucida Calligraphy} -size 12 -weight normal"  \
            " -slant roman -underline 0 -overstrike 0"
        font23 = "-family Calibri -size 15 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font25 = "-family {Lucida Calligraphy} -size 16 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("982x743+445+10")
        top.title("Matrix Mania")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.01, rely=0.013, relheight=0.969, relwidth=0.978)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#9c00f7")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.Frame1.configure(width=960)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.25, rely=0.167, height=71, width=514)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#9c00f7")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font12)
        self.Label1.configure(foreground="#fff4ad")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Matrix Mania''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.417, rely=0.111, height=51, width=214)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#9c00f7")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font25)
        self.Label2.configure(foreground="#fff4ad")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Welcome To''')
        self.Label2.configure(width=214)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.135, rely=0.764, height=52, width=101)
        self.Button1.configure(activebackground="#0000ff")
        self.Button1.configure(activeforeground="#ffffff")
        self.Button1.configure(background="#ff822e")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font23)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Start''', command=start_eqn)
        self.Button1.configure(width=101)

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.469, rely=0.764, height=52, width=94)
        self.Button2.configure(activebackground="#9dd845")
        self.Button2.configure(activeforeground="#ffffff")
        self.Button2.configure(background="#ff822e")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font23)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#262626")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Info''', command=about)
        self.Button2.configure(width=94)

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.781, rely=0.764, height=52, width=89)
        self.Button3.configure(activebackground="#ff1919")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(activeforeground="#ffffff")
        self.Button3.configure(background="#ff822e")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font23)
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Quit''', command=root.destroy)
        self.Button3.configure(width=89)

        self.Canvas1 = tk.Canvas(self.Frame1)
        self.Canvas1.place(relx=0.042, rely=0.306, relheight=0.393, relwidth=0.909)
        self.Canvas1.configure(background="#ffffff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#ffffff")
        self.Canvas1.configure(highlightcolor="#ffffff")
        self.Canvas1.configure(insertbackground="#ffffff")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#ffffff")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=873)

        self.Label3 = tk.Label(self.Canvas1)
        self.Label3.place(relx=0.011, rely=0.071, height=43, width=171)
        self.Label3.configure(activebackground="#f0f0f0")
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font15)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Designed By:''')

        self.Label4 = tk.Label(self.Canvas1)
        self.Label4.place(relx=0.025, rely=0.283, height=36, width=252)
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font20)
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(justify='left')
        self.Label4.configure(text='''-Akshaykumar Gunari''')
        self.Label4.configure(width=252)

        self.Label5 = tk.Label(self.Canvas1)
        self.Label5.place(relx=0.011, rely=0.395, height=26, width=168)
        self.Label5.configure(background="#ffffff")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font20)
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(justify='left')
        self.Label5.configure(text='''-Gourav J''')
        self.Label5.configure(width=168)

        self.Label6 = tk.Label(self.Canvas1)
        self.Label6.place(relx=0.011, rely=0.5, height=26, width=164)
        self.Label6.configure(background="#ffffff")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font20)
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(justify='left')
        self.Label6.configure(text='''-Akshata''')
        self.Label6.configure(width=164)

        self.Label7 = tk.Label(self.Canvas1)
        self.Label7.place(relx=0.023, rely=0.601, height=26, width=165)
        self.Label7.configure(background="#ffffff")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font=font20)
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''-Aarushi A''')
        self.Label7.configure(width=165)

        self.Label8 = tk.Label(self.Canvas1)
        self.Label8.place(relx=0.607, rely=0.071, height=247, width=304)
        self.Label8.configure(background="#ffffff")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self._img1 = tk.PhotoImage(file="./logo[0].png")
        self.Label8.configure(image=self._img1)
        self.Label8.configure(width=304)


class Toplevel2:
    def doRefresh(self):
        self.Entry1.delete(0, 'end')
        self.Entry2.delete(0, 'end')
        self.Entry3.delete(0, 'end')
        self.Entry4.delete(0, 'end')
        self.Entry5.delete(0, 'end')
        self.Entry6.delete(0, 'end')
        self.Entry7.delete(0, 'end')
        self.Entry8.delete(0, 'end')
        self.Entry9.delete(0, 'end')
        self.Entry10.delete(0, 'end')
        self.Entry11.delete(0, 'end')
        self.Entry12.delete(0, 'end')
        self.Entry13.delete(0, 'end')
        self.Entry14.delete(0, 'end')
        self.Entry15.delete(0, 'end')
        self.Label4.configure(text='''Rank is : ''')
        self.Label5.configure(text='''''')
        return

    def solveMatrix(self):
        condition1 = ((self.Entry1.get() is "") or (self.Entry2.get() is "") or (self.Entry3.get() is "") or (self.Entry4.get() is "") or
                      (self.Entry5.get() is "") or (self.Entry6.get() is "") or (self.Entry7.get() is "") or (self.Entry8.get() is "") or
                      (self.Entry9.get() is "") or (self.Entry10.get() is "") or (self.Entry11.get() is "") or (self.Entry12.get() is ""))

        if(condition1 is True):
            fmsgbox.showinfo("Solver", "Invalid user input. Please Check.")
            return

        try:
            matrix_a = np.array([[float(self.Entry1.get()), float(self.Entry2.get()), float(self.Entry3.get())],
                                 [float(self.Entry5.get()), float(self.Entry6.get()), float(self.Entry7.get())],
                                 [float(self.Entry9.get()), float(self.Entry10.get()), float(self.Entry11.get())]])
            matrix_ab = np.array([[float(self.Entry1.get()), float(self.Entry2.get()), float(self.Entry3.get()), float(self.Entry4.get())],
                                  [float(self.Entry5.get()), float(self.Entry6.get()), float(self.Entry7.get()), float(self.Entry8.get())],
                                  [float(self.Entry9.get()), float(self.Entry10.get()), float(self.Entry11.get()), float(self.Entry12.get())]])
            rank_a = np.linalg.matrix_rank(matrix_a)
            rank_ab = np.linalg.matrix_rank(matrix_ab)
            self.Label4.configure(text=f'''Rank is : {rank_ab}''')
        except ValueError:
            fmsgbox.showinfo("Solver", "Invalid user input.")
        else:
            if(rank_ab == rank_a):
                if(rank_a == 3):
                    # consistent system. Unique Solution exist.
                    matrix2 = np.linalg.inv(matrix_a)
                    matrix3 = np.array([float(self.Entry4.get()), float(self.Entry8.get()), float(self.Entry12.get())])
                    results = np.round(matrix2.dot(matrix3), decimals=10)
                    self.Entry13.delete(0, 'end')
                    self.Entry14.delete(0, 'end')
                    self.Entry15.delete(0, 'end')
                    self.Entry13.insert(0, results[0])
                    self.Entry14.insert(0, results[1])
                    self.Entry15.insert(0, results[2])
                    self.Label5.configure(text='''System is consistent''')
                    return
                else:
                    # infinite solutions exist.
                    self.Entry13.delete(0, 'end')
                    self.Entry14.delete(0, 'end')
                    self.Entry15.delete(0, 'end')
                    self.Label5.configure(text='''System has infinte Solutions.''')

            else:
                # system is inconsistent. No solution exist.
                self.Label5.configure(text='''System is Inconsistent''')
                self.Entry13.delete(0, 'end')
                self.Entry14.delete(0, 'end')
                self.Entry15.delete(0, 'end')

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        font10 = "-family {Franklin Gothic Medium Cond} -size 20 "  \
            "-weight bold -slant italic -underline 1 -overstrike 0"
        font11 = "-family {Segoe UI} -size 11 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family Calibri -size 14 -weight bold -slant italic "  \
            "-underline 0 -overstrike 0"
        font13 = "-family Calibri -size 14 -weight bold -slant italic "  \
            "-underline 1 -overstrike 0"
        font9 = "-family {Footlight MT Light} -size 20 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("982x743+445+10")
        top.title("Matrix Mania")
        top.configure(background="#565656")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.033, rely=0.133, height=29, width=100)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#565656")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font13)
        self.Label1.configure(foreground="#fefff7")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Equation 1 :''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.067, rely=0.2, height=20, relwidth=0.09)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.267, rely=0.2, height=20, relwidth=0.09)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.467, rely=0.2, height=20, relwidth=0.09)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Entry4 = tk.Entry(top)
        self.Entry4.place(relx=0.667, rely=0.2, height=20, relwidth=0.09)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")

        self.Message1_6 = tk.Message(top)
        self.Message1_6.place(relx=0.217, rely=0.2, relheight=0.051, relwidth=0.037)
        self.Message1_6.configure(background="#565656")
        self.Message1_6.configure(font=font11)
        self.Message1_6.configure(foreground="#ffffff")
        self.Message1_6.configure(highlightbackground="#d9d9d9")
        self.Message1_6.configure(highlightcolor="black")
        self.Message1_6.configure(text='''+''')
        self.Message1_6.configure(width=60)

        self.Message1_7 = tk.Message(top)
        self.Message1_7.place(relx=0.367, rely=0.2, relheight=0.051, relwidth=0.037)
        self.Message1_7.configure(background="#565656")
        self.Message1_7.configure(font=font11)
        self.Message1_7.configure(foreground="#ffffff")
        self.Message1_7.configure(highlightbackground="#d9d9d9")
        self.Message1_7.configure(highlightcolor="black")
        self.Message1_7.configure(text='''Y''')
        self.Message1_7.configure(width=60)

        self.Message1_8 = tk.Message(top)
        self.Message1_8.place(relx=0.417, rely=0.2, relheight=0.051, relwidth=0.037)
        self.Message1_8.configure(background="#565656")
        self.Message1_8.configure(font=font11)
        self.Message1_8.configure(foreground="#ffffff")
        self.Message1_8.configure(highlightbackground="#d9d9d9")
        self.Message1_8.configure(highlightcolor="black")
        self.Message1_8.configure(text='''+''')
        self.Message1_8.configure(width=60)

        self.Message1_9 = tk.Message(top)
        self.Message1_9.place(relx=0.567, rely=0.2, relheight=0.051, relwidth=0.037)
        self.Message1_9.configure(background="#565656")
        self.Message1_9.configure(font=font11)
        self.Message1_9.configure(foreground="#ffffff")
        self.Message1_9.configure(highlightbackground="#d9d9d9")
        self.Message1_9.configure(highlightcolor="black")
        self.Message1_9.configure(text='''Z''')
        self.Message1_9.configure(width=60)

        self.Message1_10 = tk.Message(top)
        self.Message1_10.place(relx=0.617, rely=0.2, relheight=0.051, relwidth=0.037)
        self.Message1_10.configure(background="#565656")
        self.Message1_10.configure(font=font11)
        self.Message1_10.configure(foreground="#ffffff")
        self.Message1_10.configure(highlightbackground="#d9d9d9")
        self.Message1_10.configure(highlightcolor="black")
        self.Message1_10.configure(text='''=''')
        self.Message1_10.configure(width=60)

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.033, rely=0.267, height=29, width=100)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#565656")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font13)
        self.Label1_1.configure(foreground="#ffffff")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="#000000")
        self.Label1_1.configure(text='''Equation 2:''')

        self.Entry5 = tk.Entry(top)
        self.Entry5.place(relx=0.067, rely=0.333, height=20, relwidth=0.09)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")

        self.Message1_3 = tk.Message(top)
        self.Message1_3.place(relx=0.217, rely=0.333, relheight=0.051, relwidth=0.037)
        self.Message1_3.configure(background="#565656")
        self.Message1_3.configure(font=font11)
        self.Message1_3.configure(foreground="#ffffff")
        self.Message1_3.configure(highlightbackground="#d9d9d9")
        self.Message1_3.configure(highlightcolor="black")
        self.Message1_3.configure(text='''+''')
        self.Message1_3.configure(width=60)

        self.Message1_4 = tk.Message(top)
        self.Message1_4.place(relx=0.167, rely=0.2, relheight=0.051, relwidth=0.037)
        self.Message1_4.configure(background="#565656")
        self.Message1_4.configure(font=font11)
        self.Message1_4.configure(foreground="#ffffff")
        self.Message1_4.configure(highlightbackground="#d9d9d9")
        self.Message1_4.configure(highlightcolor="black")
        self.Message1_4.configure(text='''X''')
        self.Message1_4.configure(width=22)

        self.Message1_5 = tk.Message(top)
        self.Message1_5.place(relx=0.167, rely=0.333, relheight=0.051, relwidth=0.037)
        self.Message1_5.configure(background="#565656")
        self.Message1_5.configure(font=font11)
        self.Message1_5.configure(foreground="#ffffff")
        self.Message1_5.configure(highlightbackground="#d9d9d9")
        self.Message1_5.configure(highlightcolor="black")
        self.Message1_5.configure(text='''X''')
        self.Message1_5.configure(width=22)

        self.Entry6 = tk.Entry(top)
        self.Entry6.place(relx=0.267, rely=0.333, height=20, relwidth=0.09)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")

        self.Message1_2 = tk.Message(top)
        self.Message1_2.place(relx=0.367, rely=0.333, relheight=0.051, relwidth=0.037)
        self.Message1_2.configure(background="#565656")
        self.Message1_2.configure(font=font11)
        self.Message1_2.configure(foreground="#ffffff")
        self.Message1_2.configure(highlightbackground="#d9d9d9")
        self.Message1_2.configure(highlightcolor="black")
        self.Message1_2.configure(text='''Y''')
        self.Message1_2.configure(width=60)

        self.Message1_1 = tk.Message(top)
        self.Message1_1.place(relx=0.417, rely=0.333, relheight=0.051, relwidth=0.037)
        self.Message1_1.configure(background="#565656")
        self.Message1_1.configure(font=font11)
        self.Message1_1.configure(foreground="#ffffff")
        self.Message1_1.configure(highlightbackground="#d9d9d9")
        self.Message1_1.configure(highlightcolor="black")
        self.Message1_1.configure(text='''+''')
        self.Message1_1.configure(width=60)

        self.Entry7 = tk.Entry(top)
        self.Entry7.place(relx=0.467, rely=0.333, height=20, relwidth=0.09)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")

        self.Message1_2 = tk.Message(top)
        self.Message1_2.place(relx=0.567, rely=0.333, relheight=0.051, relwidth=0.037)
        self.Message1_2.configure(background="#565656")
        self.Message1_2.configure(font=font11)
        self.Message1_2.configure(foreground="#ffffff")
        self.Message1_2.configure(highlightbackground="#d9d9d9")
        self.Message1_2.configure(highlightcolor="black")
        self.Message1_2.configure(text='''Z''')
        self.Message1_2.configure(width=60)

        self.Message1_3 = tk.Message(top)
        self.Message1_3.place(relx=0.617, rely=0.333, relheight=0.051, relwidth=0.037)
        self.Message1_3.configure(background="#565656")
        self.Message1_3.configure(font=font11)
        self.Message1_3.configure(foreground="#ffffff")
        self.Message1_3.configure(highlightbackground="#d9d9d9")
        self.Message1_3.configure(highlightcolor="black")
        self.Message1_3.configure(text='''=''')
        self.Message1_3.configure(width=60)

        self.Entry8 = tk.Entry(top)
        self.Entry8.place(relx=0.667, rely=0.333, height=20, relwidth=0.09)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(selectforeground="black")

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.033, rely=0.4, height=29, width=100)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#565656")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font13)
        self.Label1_2.configure(foreground="#ffffff")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="#000000")
        self.Label1_2.configure(text='''Equation 3:''')

        self.Entry9 = tk.Entry(top)
        self.Entry9.place(relx=0.067, rely=0.467, height=20, relwidth=0.09)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(highlightbackground="#d9d9d9")
        self.Entry9.configure(highlightcolor="black")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(selectbackground="#c4c4c4")
        self.Entry9.configure(selectforeground="black")

        self.Message1_4 = tk.Message(top)
        self.Message1_4.place(relx=0.167, rely=0.467, relheight=0.051, relwidth=0.037)
        self.Message1_4.configure(background="#565656")
        self.Message1_4.configure(font=font11)
        self.Message1_4.configure(foreground="#ffffff")
        self.Message1_4.configure(highlightbackground="#d9d9d9")
        self.Message1_4.configure(highlightcolor="black")
        self.Message1_4.configure(text='''X''')
        self.Message1_4.configure(width=22)

        self.Message1_5 = tk.Message(top)
        self.Message1_5.place(relx=0.217, rely=0.467, relheight=0.051, relwidth=0.037)
        self.Message1_5.configure(background="#565656")
        self.Message1_5.configure(font=font11)
        self.Message1_5.configure(foreground="#ffffff")
        self.Message1_5.configure(highlightbackground="#d9d9d9")
        self.Message1_5.configure(highlightcolor="black")
        self.Message1_5.configure(text='''+''')
        self.Message1_5.configure(width=60)

        self.Entry10 = tk.Entry(top)
        self.Entry10.place(relx=0.267, rely=0.467, height=20, relwidth=0.09)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(highlightbackground="#d9d9d9")
        self.Entry10.configure(highlightcolor="black")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(selectbackground="#c4c4c4")
        self.Entry10.configure(selectforeground="black")

        self.Message1_6 = tk.Message(top)
        self.Message1_6.place(relx=0.367, rely=0.467, relheight=0.051, relwidth=0.037)
        self.Message1_6.configure(background="#565656")
        self.Message1_6.configure(font=font11)
        self.Message1_6.configure(foreground="#ffffff")
        self.Message1_6.configure(highlightbackground="#d9d9d9")
        self.Message1_6.configure(highlightcolor="black")
        self.Message1_6.configure(text='''Y''')
        self.Message1_6.configure(width=60)

        self.Message1_7 = tk.Message(top)
        self.Message1_7.place(relx=0.417, rely=0.467, relheight=0.051, relwidth=0.037)
        self.Message1_7.configure(background="#565656")
        self.Message1_7.configure(font=font11)
        self.Message1_7.configure(foreground="#ffffff")
        self.Message1_7.configure(highlightbackground="#d9d9d9")
        self.Message1_7.configure(highlightcolor="black")
        self.Message1_7.configure(text='''+''')
        self.Message1_7.configure(width=22)

        self.Entry11 = tk.Entry(top)
        self.Entry11.place(relx=0.467, rely=0.467, height=20, relwidth=0.09)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(highlightbackground="#d9d9d9")
        self.Entry11.configure(highlightcolor="black")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(selectbackground="#c4c4c4")
        self.Entry11.configure(selectforeground="black")

        self.Message1_8 = tk.Message(top)
        self.Message1_8.place(relx=0.567, rely=0.467, relheight=0.051, relwidth=0.037)
        self.Message1_8.configure(background="#565656")
        self.Message1_8.configure(font=font11)
        self.Message1_8.configure(foreground="#ffffff")
        self.Message1_8.configure(highlightbackground="#d9d9d9")
        self.Message1_8.configure(highlightcolor="black")
        self.Message1_8.configure(text='''Z''')
        self.Message1_8.configure(width=60)

        self.Message1_9 = tk.Message(top)
        self.Message1_9.place(relx=0.617, rely=0.467, relheight=0.051, relwidth=0.037)
        self.Message1_9.configure(background="#565656")
        self.Message1_9.configure(font=font11)
        self.Message1_9.configure(foreground="#ffffff")
        self.Message1_9.configure(highlightbackground="#d9d9d9")
        self.Message1_9.configure(highlightcolor="black")
        self.Message1_9.configure(text='''=''')
        self.Message1_9.configure(width=60)

        self.Entry12 = tk.Entry(top)
        self.Entry12.place(relx=0.667, rely=0.467, height=20, relwidth=0.09)
        self.Entry12.configure(background="white")
        self.Entry12.configure(disabledforeground="#a3a3a3")
        self.Entry12.configure(font="TkFixedFont")
        self.Entry12.configure(foreground="#000000")
        self.Entry12.configure(highlightbackground="#d9d9d9")
        self.Entry12.configure(highlightcolor="black")
        self.Entry12.configure(insertbackground="black")
        self.Entry12.configure(selectbackground="#c4c4c4")
        self.Entry12.configure(selectforeground="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.167, rely=0.644, height=49, width=85)
        self.Button1.configure(activebackground="#98DC9A")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Solve''', command=self.solveMatrix)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.533, rely=0.644, height=49, width=103)
        self.Button2.configure(activebackground="#4F49A4")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(activeforeground="#ffffff")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font9)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Refresh''', command=self.doRefresh)

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.01, rely=0.04, height=25, width=35)
        self.Button3.configure(activebackground="#98DC9A")
        self.Button3.configure(activeforeground="#ffffff")
        self.Button3.configure(background="#98DC9A")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font12)
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="#000000")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''←''', command=go_back)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.05, rely=0.778, height=29, width=64)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#565656")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Result:''')

        self.Message1_11 = tk.Message(top)
        self.Message1_11.place(relx=0.05, rely=0.889, relheight=0.051, relwidth=0.037)
        self.Message1_11.configure(background="#565656")
        self.Message1_11.configure(font=font11)
        self.Message1_11.configure(foreground="#ffffff")
        self.Message1_11.configure(highlightbackground="#d9d9d9")
        self.Message1_11.configure(highlightcolor="black")
        self.Message1_11.configure(text='''X''')
        self.Message1_11.configure(width=22)

        self.Entry13 = tk.Entry(top)
        self.Entry13.place(relx=0.15, rely=0.889, height=20, relwidth=0.15)
        self.Entry13.configure(background="white")
        self.Entry13.configure(disabledforeground="#a3a3a3")
        self.Entry13.configure(font="TkFixedFont")
        self.Entry13.configure(foreground="#000000")
        self.Entry13.configure(highlightbackground="#d9d9d9")
        self.Entry13.configure(highlightcolor="black")
        self.Entry13.configure(insertbackground="black")
        self.Entry13.configure(selectbackground="#c4c4c4")
        self.Entry13.configure(selectforeground="black")

        self.Message1_10 = tk.Message(top)
        self.Message1_10.place(relx=0.1, rely=0.889, relheight=0.051, relwidth=0.037)
        self.Message1_10.configure(background="#565656")
        self.Message1_10.configure(font=font11)
        self.Message1_10.configure(foreground="#ffffff")
        self.Message1_10.configure(highlightbackground="#d9d9d9")
        self.Message1_10.configure(highlightcolor="black")
        self.Message1_10.configure(text='''=''')
        self.Message1_10.configure(width=60)

        self.Message1_11 = tk.Message(top)
        self.Message1_11.place(relx=0.333, rely=0.889, relheight=0.051, relwidth=0.037)
        self.Message1_11.configure(background="#565656")
        self.Message1_11.configure(font=font11)
        self.Message1_11.configure(foreground="#ffffff")
        self.Message1_11.configure(highlightbackground="#d9d9d9")
        self.Message1_11.configure(highlightcolor="black")
        self.Message1_11.configure(text='''Y''')
        self.Message1_11.configure(width=60)

        self.Message1_12 = tk.Message(top)
        self.Message1_12.place(relx=0.383, rely=0.889, relheight=0.051, relwidth=0.037)
        self.Message1_12.configure(background="#565656")
        self.Message1_12.configure(font=font11)
        self.Message1_12.configure(foreground="#ffffff")
        self.Message1_12.configure(highlightbackground="#d9d9d9")
        self.Message1_12.configure(highlightcolor="black")
        self.Message1_12.configure(text='''=''')
        self.Message1_12.configure(width=60)

        self.Entry14 = tk.Entry(top)
        self.Entry14.place(relx=0.433, rely=0.889, height=20, relwidth=0.15)
        self.Entry14.configure(background="white")
        self.Entry14.configure(disabledforeground="#a3a3a3")
        self.Entry14.configure(font="TkFixedFont")
        self.Entry14.configure(foreground="#000000")
        self.Entry14.configure(highlightbackground="#d9d9d9")
        self.Entry14.configure(highlightcolor="black")
        self.Entry14.configure(insertbackground="black")
        self.Entry14.configure(selectbackground="#c4c4c4")
        self.Entry14.configure(selectforeground="black")

        self.Message1_12 = tk.Message(top)
        self.Message1_12.place(relx=0.633, rely=0.889, relheight=0.051, relwidth=0.037)
        self.Message1_12.configure(background="#565656")
        self.Message1_12.configure(font=font11)
        self.Message1_12.configure(foreground="#ffffff")
        self.Message1_12.configure(highlightbackground="#d9d9d9")
        self.Message1_12.configure(highlightcolor="black")
        self.Message1_12.configure(text='''Z''')
        self.Message1_12.configure(width=60)

        self.Message1_13 = tk.Message(top)
        self.Message1_13.place(relx=0.683, rely=0.889, relheight=0.051, relwidth=0.037)
        self.Message1_13.configure(background="#565656")
        self.Message1_13.configure(font=font11)
        self.Message1_13.configure(foreground="#ffffff")
        self.Message1_13.configure(highlightbackground="#d9d9d9")
        self.Message1_13.configure(highlightcolor="black")
        self.Message1_13.configure(text='''=''')
        self.Message1_13.configure(width=60)

        self.Entry15 = tk.Entry(top)
        self.Entry15.place(relx=0.733, rely=0.889, height=20, relwidth=0.15)
        self.Entry15.configure(background="white")
        self.Entry15.configure(disabledforeground="#a3a3a3")
        self.Entry15.configure(font="TkFixedFont")
        self.Entry15.configure(foreground="#000000")
        self.Entry15.configure(highlightbackground="#d9d9d9")
        self.Entry15.configure(highlightcolor="black")
        self.Entry15.configure(insertbackground="black")
        self.Entry15.configure(selectbackground="#c4c4c4")
        self.Entry15.configure(selectforeground="black")

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.35, rely=0.022, height=40, width=215)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="#7c7c7c")
        self.Label3.configure(background="#565656")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="#f9f9f9")
        self.Label3.configure(text='''EQUATION SOLVER''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.35, rely=0.55, height=29, width=100)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#565656")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font13)
        self.Label4.configure(foreground="#fefff7")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="#000000")
        self.Label4.configure(text='''Rank is : ''')

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.25, rely=0.95, height=29, width=300)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#565656")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font13)
        self.Label5.configure(foreground="#fefff7")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="#000000")


class Toplevel3:

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        font12 = "-family Meiryo -size 14 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font13 = "-family {Meiryo UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font16 = "-family Fixedsys -size 14 -weight bold -slant roman "  \
            "-underline 1 -overstrike 0"
        font17 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family Fixedsys -size 22 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("982x743+445+10")
        top.title("Matrix Mania")
        top.configure(background="#3f7cd8")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.013, rely=0.033, height=56, width=172)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#3f7cd8")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#e6c9ff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''About :''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.088, rely=0.132, height=40, width=624)
        self.Label2.configure(background="#3f7cd8")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(text='''This project was made as a part of open ended activity''')
        self.Label2.configure(width=624)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.013, rely=0.792, height=26, width=225)
        self.Label3.configure(background="#3f7cd8")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font16)
        self.Label3.configure(foreground="#e6c9ff")
        self.Label3.configure(highlightbackground="#f0f0f0")
        self.Label3.configure(text='''Course Instructor :''')
        self.Label3.configure(width=225)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.734, rely=0.792, height=30, width=103)
        self.Label4.configure(background="#3f7cd8")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font16)
        self.Label4.configure(foreground="#e6c9ff")
        self.Label4.configure(text='''Guide :''')
        self.Label4.configure(width=103)

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.075, rely=0.842, height=37, width=122)
        self.Label5.configure(background="#3f7cd8")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font17)
        self.Label5.configure(foreground="#ffffff")
        self.Label5.configure(text='''Madhura S''')

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.684, rely=0.832, height=66, width=242)
        self.Label6.configure(background="#3f7cd8")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font17)
        self.Label6.configure(foreground="#ffffff")
        self.Label6.configure(text='''K.M.M Rajashekariah''')
        self.Label6.configure(width=242)

        self.Label7 = tk.Label(top)
        self.Label7.place(relx=0.189, rely=0.198, height=35, width=464)
        self.Label7.configure(background="#3f7cd8")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font=font13)
        self.Label7.configure(foreground="#ffffff")
        self.Label7.configure(text='''at SoCSE, KLE Technological University.''')

        self.Label8 = tk.Label(top)
        self.Label8.place(relx=0.553, rely=0.297, height=265, width=277)
        self.Label8.configure(background="#3f7cd8")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self._img1 = tk.PhotoImage(file="kletech_logo.png")
        self.Label8.configure(image=self._img1)
        self.Label8.configure(text='''Label''')
        self.Label8.configure(width=277)

        self.Label9 = tk.Label(top)
        self.Label9.place(relx=0.075, rely=0.297, height=267, width=284)
        self.Label9.configure(background="#ffffff")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self._img2 = tk.PhotoImage(file="./logo[0].png")
        self.Label9.configure(image=self._img2)
        self.Label9.configure(text='''Label''')
        self.Label9.configure(width=284)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.45, rely=0.855, height=49, width=103)
        self.Button2.configure(activebackground="#9dd845")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#ff822e")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font13)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#262626")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Back''', command=go_back)


if __name__ == '__main__':
    start_gui()
