#############################################################################
# Generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#  Nov 27, 2018 08:42:20 AM +0530  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family Calibri -size 14 -weight bold -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family Calibri -size 14 -weight bold -slant italic -underline 1 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Footlight MT Light} -size 20 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Franklin Gothic Medium Cond} -size 20 -weight bold -slant italic -underline 1 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m88" -background {#565656} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+557+153
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1436 873
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "EQUATION SOLVER"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#565656} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#fefff7} \
        -highlightbackground {#d9d9d9} -highlightcolor {#000000} \
        -text {Equation 1 :} 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent48" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent49" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent50" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes54 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text + -width 60 
    vTcl:DefineAlias "$top.mes54" "Message1_6" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes55 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Y -width 60 
    vTcl:DefineAlias "$top.mes55" "Message1_7" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes56 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text + -width 60 
    vTcl:DefineAlias "$top.mes56" "Message1_8" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes57 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Z -width 60 
    vTcl:DefineAlias "$top.mes57" "Message1_9" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes58 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text = -width 60 
    vTcl:DefineAlias "$top.mes58" "Message1_10" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#565656} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor {#000000} \
        -text {Equation 2:} 
    vTcl:DefineAlias "$top.lab44" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent45" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent46 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent46" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes47 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text + -width 60 
    vTcl:DefineAlias "$top.mes47" "Message1_3" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes48 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text X -width 22 
    vTcl:DefineAlias "$top.mes48" "Message1_4" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes49 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text X -width 22 
    vTcl:DefineAlias "$top.mes49" "Message1_5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent51 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent51" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes53 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Y -width 60 
    vTcl:DefineAlias "$top.mes53" "Message1_2" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes59 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text + -width 60 
    vTcl:DefineAlias "$top.mes59" "Message1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent60 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent60" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes61 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Z -width 60 
    vTcl:DefineAlias "$top.mes61" "Message1_1" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes62 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text = -width 60 
    vTcl:DefineAlias "$top.mes62" "Message1_2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent63 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent63" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#565656} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor {#000000} \
        -text {Equation 3:} 
    vTcl:DefineAlias "$top.lab64" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent65 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent65" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes66 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text X -width 22 
    vTcl:DefineAlias "$top.mes66" "Message1_3" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes67 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text + -width 60 
    vTcl:DefineAlias "$top.mes67" "Message1_4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent68 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent68" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes69 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Y -width 60 
    vTcl:DefineAlias "$top.mes69" "Message1_5" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes70 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text + -width 22 
    vTcl:DefineAlias "$top.mes70" "Message1_6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent71 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent71" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes72 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Z -width 60 
    vTcl:DefineAlias "$top.mes72" "Message1_7" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes73 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text = -width 60 
    vTcl:DefineAlias "$top.mes73" "Message1_8" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent74 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent74" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    button $top.but75 \
        -activebackground {#98DC9A} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor {#000000} -pady 0 \
        -text Solve 
    vTcl:DefineAlias "$top.but75" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but76 \
        -activebackground {#4F49A4} -activeforeground {#ffffff} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor {#000000} -pady 0 \
        -text Refresh 
    vTcl:DefineAlias "$top.but76" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab77 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#565656} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font11,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Result: } 
    vTcl:DefineAlias "$top.lab77" "Label2" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes78 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text X -width 22 
    vTcl:DefineAlias "$top.mes78" "Message1_11" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent79 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent79" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes81 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text = -width 60 
    vTcl:DefineAlias "$top.mes81" "Message1_9" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes82 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Y -width 60 
    vTcl:DefineAlias "$top.mes82" "Message1_10" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes83 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text = -width 60 
    vTcl:DefineAlias "$top.mes83" "Message1_12" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent84 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent84" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes85 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Z -width 60 
    vTcl:DefineAlias "$top.mes85" "Message1_11" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes86 \
        -background {#565656} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text = -width 60 
    vTcl:DefineAlias "$top.mes86" "Message1_13" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent87 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent87" "Entry15" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m88
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground {#7c7c7c} \
        -background {#565656} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor {#f9f9f9} \
        -text {EQUATION SOLVER} 
    vTcl:DefineAlias "$top.lab43" "Label3" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 20 -y 60 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 160 -y 90 -width 54 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 280 -y 90 -width 54 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 400 -y 90 -width 54 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes54 \
        -in $top -x 130 -y 90 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes55 \
        -in $top -x 220 -y 90 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes56 \
        -in $top -x 250 -y 90 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes57 \
        -in $top -x 340 -y 90 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes58 \
        -in $top -x 370 -y 90 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.lab44 \
        -in $top -x 20 -y 120 -width 100 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.ent45 \
        -in $top -x 40 -y 90 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent46 \
        -in $top -x 40 -y 150 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.mes47 \
        -in $top -x 130 -y 150 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes48 \
        -in $top -x 100 -y 90 -width 22 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes49 \
        -in $top -x 100 -y 150 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent51 \
        -in $top -x 160 -y 150 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.mes53 \
        -in $top -x 220 -y 150 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes59 \
        -in $top -x 250 -y 150 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent60 \
        -in $top -x 280 -y 150 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.mes61 \
        -in $top -x 340 -y 150 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes62 \
        -in $top -x 370 -y 150 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent63 \
        -in $top -x 400 -y 150 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab64 \
        -in $top -x 20 -y 180 -width 100 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.ent65 \
        -in $top -x 40 -y 210 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.mes66 \
        -in $top -x 100 -y 210 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes67 \
        -in $top -x 130 -y 210 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent68 \
        -in $top -x 160 -y 210 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.mes69 \
        -in $top -x 220 -y 210 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes70 \
        -in $top -x 250 -y 210 -width 22 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent71 \
        -in $top -x 280 -y 210 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.mes72 \
        -in $top -x 340 -y 210 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes73 \
        -in $top -x 370 -y 210 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent74 \
        -in $top -x 400 -y 210 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.but75 \
        -in $top -x 100 -y 290 -anchor nw -bordermode ignore 
    place $top.but76 \
        -in $top -x 320 -y 290 -width 103 -height 49 -anchor nw \
        -bordermode ignore 
    place $top.lab77 \
        -in $top -x 30 -y 350 -anchor nw -bordermode ignore 
    place $top.mes78 \
        -in $top -x 30 -y 400 -width 22 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent79 \
        -in $top -x 90 -y 400 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.mes81 \
        -in $top -x 60 -y 400 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes82 \
        -in $top -x 200 -y 400 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes83 \
        -in $top -x 230 -y 400 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent84 \
        -in $top -x 260 -y 400 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.mes85 \
        -in $top -x 380 -y 400 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.mes86 \
        -in $top -x 410 -y 400 -width 22 -height 23 -anchor nw \
        -bordermode ignore 
    place $top.ent87 \
        -in $top -x 440 -y 400 -width 54 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab43 \
        -in $top -x 150 -y 10 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

