#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 23, 2018 11:04:48 AM +0530  platform: Windows NT

import sys
import numpy as np
import tkinter.messagebox as fmsgbox 

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
   
    py3 = True

import SLP_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, END, root
    root = tk.Tk()
    top = Toplevel1 (root)
    SLP_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    SLP_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroys()
    w = None

class Toplevel1:
    def doRefresh(self):
        self.Entry1.delete(0,'end')
        self.Entry2.delete(0,'end')
        self.Entry3.delete(0,'end')
        self.Entry4.delete(0,'end')
        self.Entry5.delete(0,'end')
        self.Entry6.delete(0,'end')
        self.Entry7.delete(0,'end')
        self.Entry8.delete(0,'end')
        self.Entry9.delete(0,'end')
        self.Entry10.delete(0,'end')
        self.Entry11.delete(0,'end')
        self.Entry12.delete(0,'end')
        self.Entry13.delete(0,'end')
        self.Entry14.delete(0,'end')
        self.Entry15.delete(0,'end')
        return
    def solveMatrix(self):
        condition1 = ((self.Entry1.get() is "") or (self.Entry2.get() is "") or (self.Entry3.get() is "") or (self.Entry4.get() is "") or (self.Entry5.get() is "") or (self.Entry6.get() is "") or (self.Entry7.get() is "") or (self.Entry8.get() is "") or (self.Entry9.get() is "") or (self.Entry10.get() is "") or (self.Entry11.get() is "") or (self.Entry12.get() is ""))
        if(condition1 is True):
            fmsgbox.showinfo("Solver","Invalid user input. Please Check.")
            return
        matrix1=np.array([[float(self.Entry1.get()),float(self.Entry2.get()),float(self.Entry3.get())],
                          [float(self.Entry5.get()),float(self.Entry6.get()),float(self.Entry7.get())],
                          [float(self.Entry9.get()),float(self.Entry10.get()),float(self.Entry11.get())]])
    
    
    
        try:
            matrix2 = np.linalg.inv(matrix1)
        except np.linalg.LinAlgError as err:
            if 'Singular matrix' in str(err):
                fmsgbox.showinfo("Invalid Input!","No two Equations can be same.")
            else:
                raise
        matrix3 = np.array([float(self.Entry4.get()),float(self.Entry8.get()),float(self.Entry12.get())])
        results = np.round(matrix2.dot(matrix3),decimals=10)
        self.Entry13.insert(0,results[0])
        self.Entry14.insert(0,results[1])
        self.Entry15.insert(0,results[2])
        return
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Franklin Gothic Medium Cond} -size 20 "  \
            "-weight bold -slant italic -underline 1 -overstrike 0"
        font11 = "-family {Segoe UI} -size 11 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family Calibri -size 14 -weight bold -slant italic "  \
            "-underline 0 -overstrike 0"
        font13 = "-family Calibri -size 14 -weight bold -slant italic "  \
            "-underline 1 -overstrike 0"
        font9 = "-family {Footlight MT Light} -size 20 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("600x450+557+153")
        top.title("Matrix Mania")
        top.configure(background="#565656")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.033, rely=0.133, height=29, width=100)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#565656")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font13)
        self.Label1.configure(foreground="#fefff7")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Equation 1 :''')

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.267, rely=0.2,height=20, relwidth=0.09)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.467, rely=0.2,height=20, relwidth=0.09)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Entry4 = tk.Entry(top)
        self.Entry4.place(relx=0.667, rely=0.2,height=20, relwidth=0.09)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")

        self.Message1_6 = tk.Message(top)
        self.Message1_6.place(relx=0.217, rely=0.2, relheight=0.051
                , relwidth=0.037)
        self.Message1_6.configure(background="#565656")
        self.Message1_6.configure(font=font11)
        self.Message1_6.configure(foreground="#ffffff")
        self.Message1_6.configure(highlightbackground="#d9d9d9")
        self.Message1_6.configure(highlightcolor="black")
        self.Message1_6.configure(text='''+''')
        self.Message1_6.configure(width=60)

        self.Message1_7 = tk.Message(top)
        self.Message1_7.place(relx=0.367, rely=0.2, relheight=0.051
                , relwidth=0.037)
        self.Message1_7.configure(background="#565656")
        self.Message1_7.configure(font=font11)
        self.Message1_7.configure(foreground="#ffffff")
        self.Message1_7.configure(highlightbackground="#d9d9d9")
        self.Message1_7.configure(highlightcolor="black")
        self.Message1_7.configure(text='''Y''')
        self.Message1_7.configure(width=60)

        self.Message1_8 = tk.Message(top)
        self.Message1_8.place(relx=0.417, rely=0.2, relheight=0.051
                , relwidth=0.037)
        self.Message1_8.configure(background="#565656")
        self.Message1_8.configure(font=font11)
        self.Message1_8.configure(foreground="#ffffff")
        self.Message1_8.configure(highlightbackground="#d9d9d9")
        self.Message1_8.configure(highlightcolor="black")
        self.Message1_8.configure(text='''+''')
        self.Message1_8.configure(width=60)

        self.Message1_9 = tk.Message(top)
        self.Message1_9.place(relx=0.567, rely=0.2, relheight=0.051
                , relwidth=0.037)
        self.Message1_9.configure(background="#565656")
        self.Message1_9.configure(font=font11)
        self.Message1_9.configure(foreground="#ffffff")
        self.Message1_9.configure(highlightbackground="#d9d9d9")
        self.Message1_9.configure(highlightcolor="black")
        self.Message1_9.configure(text='''Z''')
        self.Message1_9.configure(width=60)

        self.Message1_10 = tk.Message(top)
        self.Message1_10.place(relx=0.617, rely=0.2, relheight=0.051
                , relwidth=0.037)
        self.Message1_10.configure(background="#565656")
        self.Message1_10.configure(font=font11)
        self.Message1_10.configure(foreground="#ffffff")
        self.Message1_10.configure(highlightbackground="#d9d9d9")
        self.Message1_10.configure(highlightcolor="black")
        self.Message1_10.configure(text='''=''')
        self.Message1_10.configure(width=60)

        self.Label1_1 = tk.Label(top)
        self.Label1_1.place(relx=0.033, rely=0.267, height=29, width=100)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#565656")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font=font13)
        self.Label1_1.configure(foreground="#ffffff")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="#000000")
        self.Label1_1.configure(text='''Equation 2:''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.067, rely=0.2,height=20, relwidth=0.09)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Entry5 = tk.Entry(top)
        self.Entry5.place(relx=0.067, rely=0.333,height=20, relwidth=0.09)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")

        self.Message1_3 = tk.Message(top)
        self.Message1_3.place(relx=0.217, rely=0.333, relheight=0.051
                , relwidth=0.037)
        self.Message1_3.configure(background="#565656")
        self.Message1_3.configure(font=font11)
        self.Message1_3.configure(foreground="#ffffff")
        self.Message1_3.configure(highlightbackground="#d9d9d9")
        self.Message1_3.configure(highlightcolor="black")
        self.Message1_3.configure(text='''+''')
        self.Message1_3.configure(width=60)

        self.Message1_4 = tk.Message(top)
        self.Message1_4.place(relx=0.167, rely=0.2, relheight=0.051
                , relwidth=0.037)
        self.Message1_4.configure(background="#565656")
        self.Message1_4.configure(font=font11)
        self.Message1_4.configure(foreground="#ffffff")
        self.Message1_4.configure(highlightbackground="#d9d9d9")
        self.Message1_4.configure(highlightcolor="black")
        self.Message1_4.configure(text='''X''')
        self.Message1_4.configure(width=22)

        self.Message1_5 = tk.Message(top)
        self.Message1_5.place(relx=0.167, rely=0.333, relheight=0.051
                , relwidth=0.037)
        self.Message1_5.configure(background="#565656")
        self.Message1_5.configure(font=font11)
        self.Message1_5.configure(foreground="#ffffff")
        self.Message1_5.configure(highlightbackground="#d9d9d9")
        self.Message1_5.configure(highlightcolor="black")
        self.Message1_5.configure(text='''X''')
        self.Message1_5.configure(width=22)

        self.Entry6 = tk.Entry(top)
        self.Entry6.place(relx=0.267, rely=0.333,height=20, relwidth=0.09)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(highlightbackground="#d9d9d9")
        self.Entry6.configure(highlightcolor="black")
        self.Entry6.configure(insertbackground="black")
        self.Entry6.configure(selectbackground="#c4c4c4")
        self.Entry6.configure(selectforeground="black")

        self.Message1_2 = tk.Message(top)
        self.Message1_2.place(relx=0.367, rely=0.333, relheight=0.051
                , relwidth=0.037)
        self.Message1_2.configure(background="#565656")
        self.Message1_2.configure(font=font11)
        self.Message1_2.configure(foreground="#ffffff")
        self.Message1_2.configure(highlightbackground="#d9d9d9")
        self.Message1_2.configure(highlightcolor="black")
        self.Message1_2.configure(text='''Y''')
        self.Message1_2.configure(width=60)

        self.Message1_1 = tk.Message(top)
        self.Message1_1.place(relx=0.417, rely=0.333, relheight=0.051
                , relwidth=0.037)
        self.Message1_1.configure(background="#565656")
        self.Message1_1.configure(font=font11)
        self.Message1_1.configure(foreground="#ffffff")
        self.Message1_1.configure(highlightbackground="#d9d9d9")
        self.Message1_1.configure(highlightcolor="black")
        self.Message1_1.configure(text='''+''')
        self.Message1_1.configure(width=60)

        self.Entry7 = tk.Entry(top)
        self.Entry7.place(relx=0.467, rely=0.333,height=20, relwidth=0.09)
        self.Entry7.configure(background="white")
        self.Entry7.configure(disabledforeground="#a3a3a3")
        self.Entry7.configure(font="TkFixedFont")
        self.Entry7.configure(foreground="#000000")
        self.Entry7.configure(highlightbackground="#d9d9d9")
        self.Entry7.configure(highlightcolor="black")
        self.Entry7.configure(insertbackground="black")
        self.Entry7.configure(selectbackground="#c4c4c4")
        self.Entry7.configure(selectforeground="black")

        self.Message1_2 = tk.Message(top)
        self.Message1_2.place(relx=0.567, rely=0.333, relheight=0.051
                , relwidth=0.037)
        self.Message1_2.configure(background="#565656")
        self.Message1_2.configure(font=font11)
        self.Message1_2.configure(foreground="#ffffff")
        self.Message1_2.configure(highlightbackground="#d9d9d9")
        self.Message1_2.configure(highlightcolor="black")
        self.Message1_2.configure(text='''Z''')
        self.Message1_2.configure(width=60)

        self.Message1_3 = tk.Message(top)
        self.Message1_3.place(relx=0.617, rely=0.333, relheight=0.051
                , relwidth=0.037)
        self.Message1_3.configure(background="#565656")
        self.Message1_3.configure(font=font11)
        self.Message1_3.configure(foreground="#ffffff")
        self.Message1_3.configure(highlightbackground="#d9d9d9")
        self.Message1_3.configure(highlightcolor="black")
        self.Message1_3.configure(text='''=''')
        self.Message1_3.configure(width=60)

        self.Entry8 = tk.Entry(top)
        self.Entry8.place(relx=0.667, rely=0.333,height=20, relwidth=0.09)
        self.Entry8.configure(background="white")
        self.Entry8.configure(disabledforeground="#a3a3a3")
        self.Entry8.configure(font="TkFixedFont")
        self.Entry8.configure(foreground="#000000")
        self.Entry8.configure(highlightbackground="#d9d9d9")
        self.Entry8.configure(highlightcolor="black")
        self.Entry8.configure(insertbackground="black")
        self.Entry8.configure(selectbackground="#c4c4c4")
        self.Entry8.configure(selectforeground="black")

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.033, rely=0.4, height=29, width=100)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#565656")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font=font13)
        self.Label1_2.configure(foreground="#ffffff")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="#000000")
        self.Label1_2.configure(text='''Equation 3:''')

        self.Entry9 = tk.Entry(top)
        self.Entry9.place(relx=0.067, rely=0.467,height=20, relwidth=0.09)
        self.Entry9.configure(background="white")
        self.Entry9.configure(disabledforeground="#a3a3a3")
        self.Entry9.configure(font="TkFixedFont")
        self.Entry9.configure(foreground="#000000")
        self.Entry9.configure(highlightbackground="#d9d9d9")
        self.Entry9.configure(highlightcolor="black")
        self.Entry9.configure(insertbackground="black")
        self.Entry9.configure(selectbackground="#c4c4c4")
        self.Entry9.configure(selectforeground="black")

        self.Message1_4 = tk.Message(top)
        self.Message1_4.place(relx=0.167, rely=0.467, relheight=0.051
                , relwidth=0.037)
        self.Message1_4.configure(background="#565656")
        self.Message1_4.configure(font=font11)
        self.Message1_4.configure(foreground="#ffffff")
        self.Message1_4.configure(highlightbackground="#d9d9d9")
        self.Message1_4.configure(highlightcolor="black")
        self.Message1_4.configure(text='''X''')
        self.Message1_4.configure(width=22)

        self.Message1_5 = tk.Message(top)
        self.Message1_5.place(relx=0.217, rely=0.467, relheight=0.051
                , relwidth=0.037)
        self.Message1_5.configure(background="#565656")
        self.Message1_5.configure(font=font11)
        self.Message1_5.configure(foreground="#ffffff")
        self.Message1_5.configure(highlightbackground="#d9d9d9")
        self.Message1_5.configure(highlightcolor="black")
        self.Message1_5.configure(text='''+''')
        self.Message1_5.configure(width=60)

        self.Entry10 = tk.Entry(top)
        self.Entry10.place(relx=0.267, rely=0.467,height=20, relwidth=0.09)
        self.Entry10.configure(background="white")
        self.Entry10.configure(disabledforeground="#a3a3a3")
        self.Entry10.configure(font="TkFixedFont")
        self.Entry10.configure(foreground="#000000")
        self.Entry10.configure(highlightbackground="#d9d9d9")
        self.Entry10.configure(highlightcolor="black")
        self.Entry10.configure(insertbackground="black")
        self.Entry10.configure(selectbackground="#c4c4c4")
        self.Entry10.configure(selectforeground="black")

        self.Message1_6 = tk.Message(top)
        self.Message1_6.place(relx=0.367, rely=0.467, relheight=0.051
                , relwidth=0.037)
        self.Message1_6.configure(background="#565656")
        self.Message1_6.configure(font=font11)
        self.Message1_6.configure(foreground="#ffffff")
        self.Message1_6.configure(highlightbackground="#d9d9d9")
        self.Message1_6.configure(highlightcolor="black")
        self.Message1_6.configure(text='''Y''')
        self.Message1_6.configure(width=60)

        self.Message1_7 = tk.Message(top)
        self.Message1_7.place(relx=0.417, rely=0.467, relheight=0.051
                , relwidth=0.037)
        self.Message1_7.configure(background="#565656")
        self.Message1_7.configure(font=font11)
        self.Message1_7.configure(foreground="#ffffff")
        self.Message1_7.configure(highlightbackground="#d9d9d9")
        self.Message1_7.configure(highlightcolor="black")
        self.Message1_7.configure(text='''+''')
        self.Message1_7.configure(width=22)

        self.Entry11 = tk.Entry(top)
        self.Entry11.place(relx=0.467, rely=0.467,height=20, relwidth=0.09)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(highlightbackground="#d9d9d9")
        self.Entry11.configure(highlightcolor="black")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(selectbackground="#c4c4c4")
        self.Entry11.configure(selectforeground="black")

        self.Message1_8 = tk.Message(top)
        self.Message1_8.place(relx=0.567, rely=0.467, relheight=0.051
                , relwidth=0.037)
        self.Message1_8.configure(background="#565656")
        self.Message1_8.configure(font=font11)
        self.Message1_8.configure(foreground="#ffffff")
        self.Message1_8.configure(highlightbackground="#d9d9d9")
        self.Message1_8.configure(highlightcolor="black")
        self.Message1_8.configure(text='''Z''')
        self.Message1_8.configure(width=60)

        self.Message1_9 = tk.Message(top)
        self.Message1_9.place(relx=0.617, rely=0.467, relheight=0.051
                , relwidth=0.037)
        self.Message1_9.configure(background="#565656")
        self.Message1_9.configure(font=font11)
        self.Message1_9.configure(foreground="#ffffff")
        self.Message1_9.configure(highlightbackground="#d9d9d9")
        self.Message1_9.configure(highlightcolor="black")
        self.Message1_9.configure(text='''=''')
        self.Message1_9.configure(width=60)

        self.Entry12 = tk.Entry(top)
        self.Entry12.place(relx=0.667, rely=0.467,height=20, relwidth=0.09)
        self.Entry12.configure(background="white")
        self.Entry12.configure(disabledforeground="#a3a3a3")
        self.Entry12.configure(font="TkFixedFont")
        self.Entry12.configure(foreground="#000000")
        self.Entry12.configure(highlightbackground="#d9d9d9")
        self.Entry12.configure(highlightcolor="black")
        self.Entry12.configure(insertbackground="black")
        self.Entry12.configure(selectbackground="#c4c4c4")
        self.Entry12.configure(selectforeground="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.167, rely=0.644, height=49, width=85)
        self.Button1.configure(activebackground="#98DC9A")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="#000000")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Solve''',command=self.solveMatrix)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.533, rely=0.644, height=49, width=103)
        self.Button2.configure(activebackground="#4F49A4")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(activeforeground="#ffffff")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font9)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="#000000")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Refresh''',command=self.doRefresh)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.05, rely=0.778, height=29, width=64)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#565656")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Result:''')

        self.Message1_11 = tk.Message(top)
        self.Message1_11.place(relx=0.05, rely=0.889, relheight=0.051
                , relwidth=0.037)
        self.Message1_11.configure(background="#565656")
        self.Message1_11.configure(font=font11)
        self.Message1_11.configure(foreground="#ffffff")
        self.Message1_11.configure(highlightbackground="#d9d9d9")
        self.Message1_11.configure(highlightcolor="black")
        self.Message1_11.configure(text='''X''')
        self.Message1_11.configure(width=22)

        self.Entry13 = tk.Entry(top)
        self.Entry13.place(relx=0.15, rely=0.889,height=20, relwidth=0.15)
        self.Entry13.configure(background="white")
        self.Entry13.configure(disabledforeground="#a3a3a3")
        self.Entry13.configure(font="TkFixedFont")
        self.Entry13.configure(foreground="#000000")
        self.Entry13.configure(highlightbackground="#d9d9d9")
        self.Entry13.configure(highlightcolor="black")
        self.Entry13.configure(insertbackground="black")
        self.Entry13.configure(selectbackground="#c4c4c4")
        self.Entry13.configure(selectforeground="black")

        self.Message1_10 = tk.Message(top)
        self.Message1_10.place(relx=0.1, rely=0.889, relheight=0.051
                , relwidth=0.037)
        self.Message1_10.configure(background="#565656")
        self.Message1_10.configure(font=font11)
        self.Message1_10.configure(foreground="#ffffff")
        self.Message1_10.configure(highlightbackground="#d9d9d9")
        self.Message1_10.configure(highlightcolor="black")
        self.Message1_10.configure(text='''=''')
        self.Message1_10.configure(width=60)

        self.Message1_11 = tk.Message(top)
        self.Message1_11.place(relx=0.333, rely=0.889, relheight=0.051
                , relwidth=0.037)
        self.Message1_11.configure(background="#565656")
        self.Message1_11.configure(font=font11)
        self.Message1_11.configure(foreground="#ffffff")
        self.Message1_11.configure(highlightbackground="#d9d9d9")
        self.Message1_11.configure(highlightcolor="black")
        self.Message1_11.configure(text='''Y''')
        self.Message1_11.configure(width=60)

        self.Message1_12 = tk.Message(top)
        self.Message1_12.place(relx=0.383, rely=0.889, relheight=0.051
                , relwidth=0.037)
        self.Message1_12.configure(background="#565656")
        self.Message1_12.configure(font=font11)
        self.Message1_12.configure(foreground="#ffffff")
        self.Message1_12.configure(highlightbackground="#d9d9d9")
        self.Message1_12.configure(highlightcolor="black")
        self.Message1_12.configure(text='''=''')
        self.Message1_12.configure(width=60)

        self.Entry14 = tk.Entry(top)
        self.Entry14.place(relx=0.433, rely=0.889,height=20, relwidth=0.15)
        self.Entry14.configure(background="white")
        self.Entry14.configure(disabledforeground="#a3a3a3")
        self.Entry14.configure(font="TkFixedFont")
        self.Entry14.configure(foreground="#000000")
        self.Entry14.configure(highlightbackground="#d9d9d9")
        self.Entry14.configure(highlightcolor="black")
        self.Entry14.configure(insertbackground="black")
        self.Entry14.configure(selectbackground="#c4c4c4")
        self.Entry14.configure(selectforeground="black")

        self.Message1_12 = tk.Message(top)
        self.Message1_12.place(relx=0.633, rely=0.889, relheight=0.051
                , relwidth=0.037)
        self.Message1_12.configure(background="#565656")
        self.Message1_12.configure(font=font11)
        self.Message1_12.configure(foreground="#ffffff")
        self.Message1_12.configure(highlightbackground="#d9d9d9")
        self.Message1_12.configure(highlightcolor="black")
        self.Message1_12.configure(text='''Z''')
        self.Message1_12.configure(width=60)

        self.Message1_13 = tk.Message(top)
        self.Message1_13.place(relx=0.683, rely=0.889, relheight=0.051
                , relwidth=0.037)
        self.Message1_13.configure(background="#565656")
        self.Message1_13.configure(font=font11)
        self.Message1_13.configure(foreground="#ffffff")
        self.Message1_13.configure(highlightbackground="#d9d9d9")
        self.Message1_13.configure(highlightcolor="black")
        self.Message1_13.configure(text='''=''')
        self.Message1_13.configure(width=60)

        self.Entry15 = tk.Entry(top)
        self.Entry15.place(relx=0.733, rely=0.889,height=20, relwidth=0.15)
        self.Entry15.configure(background="white")
        self.Entry15.configure(disabledforeground="#a3a3a3")
        self.Entry15.configure(font="TkFixedFont")
        self.Entry15.configure(foreground="#000000")
        self.Entry15.configure(highlightbackground="#d9d9d9")
        self.Entry15.configure(highlightcolor="black")
        self.Entry15.configure(insertbackground="black")
        self.Entry15.configure(selectbackground="#c4c4c4")
        self.Entry15.configure(selectforeground="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.25, rely=0.022, height=40, width=205)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="#7c7c7c")
        self.Label3.configure(background="#565656")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="#f9f9f9")
        self.Label3.configure(text='''EQUATION SOLVER''')

if __name__ == '__main__':
    vp_start_gui()





